name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: 'This issue is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 2 days.'
          stale-pr-message: 'This PR is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 2 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 2 days with no activity.'
          days-before-issue-stale: 5
          days-before-pr-stale: 5
          days-before-issue-close: 2
          days-before-pr-close: 2
          exempt-issue-labels: 'bug,feature,help wanted,invalid'
          exempt-all-assignees: true